
#Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password:
  #    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

#Server
server:
  port: 3311


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always



